import streamlit as st
import random

# Set the app title without any icon
st.set_page_config(page_title="Jokes Generator")
st.title("Jokes Generator")
st.write("Click the button to get a new joke every time!")

# 100 jokes list
jokes = [
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "I told my computer I needed a break, and it said 'No problem – I’ll go to sleep.'",
    "Why don’t skeletons fight each other? They don’t have the guts.",
    "Parallel lines have so much in common… it’s a shame they’ll never meet.",
    "I asked the gym instructor if he could teach me to do the splits. He said, 'How flexible are you?' I said, 'I can’t make it on Tuesdays.'",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "Why don’t scientists trust atoms? Because they make up everything.",
    "I’m reading a book about anti-gravity. It’s impossible to put down.",
    "Why did the math book look sad? Because it had too many problems.",
    "Why can’t your nose be 12 inches long? Because then it would be a foot.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "Why did the bicycle fall over? Because it was two-tired.",
    "I would tell you a construction joke, but I’m still working on it.",
    "Why did the coffee file a police report? It got mugged.",
    "Why did the computer go to the doctor? Because it caught a virus!",
    "Why did the chicken go to the seance? To talk to the other side.",
    "I told my dog to play fetch, but he just kept chasing his tail. Talk about a vicious cycle!",
    "Why did the cookie go to the hospital? Because he felt crummy.",
    "I bought some shoes from a drug dealer. I don’t know what he laced them with, but I was tripping all day.",
    "I’m on a seafood diet. I see food and I eat it.",
    "Why did the ghost go to school? To learn how to be transparent.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "Why was the math teacher late to work? She took the rhombus.",
    "I told my friend 10 jokes to get him to laugh. Sadly, no pun in ten did.",
    "Why was the belt arrested? For holding up a pair of pants.",
    "Why did the stadium get hot after the game? All the fans left.",
    "Why did the musician get locked out of his house? He couldn’t find the keys.",
    "I asked the librarian if books about paranoia were available. She whispered, 'They’re right behind you.'",
    "Why did the orange stop? It ran out of juice.",
    "Why don’t eggs tell jokes? They’d crack each other up.",
    "I tried to catch fog yesterday. Mist.",
    "Why was the broom late? It swept in.",
    "I told my friend he drew his eyebrows too high. He seemed surprised.",
    "Why did the man put his money in the blender? He wanted to make liquid assets.",
    "Why did the vampire read the newspaper? He heard it had great circulation.",
    "Why did the scarecrow get promoted? Because he was outstanding in his field.",
    "Why do bees have sticky hair? Because they use honeycombs.",
    "Why don’t oysters share their pearls? Because they’re shellfish.",
    "Why did the skeleton go to the party alone? He had no body to go with.",
    "What do you call fake spaghetti? An impasta.",
    "Why did the tomato blush? Because it saw the salad dressing.",
    "Why can’t your nose be 12 inches long? Because then it would be a foot.",
    "Why did the man put his money in the freezer? He wanted cold hard cash.",
    "Why did the chicken cross the playground? To get to the other slide.",
    "Why don’t crabs give to charity? Because they’re shellfish.",
    "Why did the banana go to the doctor? Because it wasn’t peeling well.",
    "Why did the coffee file a police report? It got mugged.",
    "Why was the computer cold? It left its Windows open.",
    "Why did the math book look sad? Because it had too many problems.",
    "Why did the golfer bring extra socks? In case he got a hole in one.",
    "Why did the physics teacher break up with the biology teacher? There was no chemistry.",
    "Why did the fish blush? Because it saw the ocean’s bottom.",
    "Why was the broom late? It over-swept.",
    "Why did the chicken join a band? Because it had the drumsticks.",
    "Why don’t scientists trust atoms? They make up everything.",
    "Why did the picture go to jail? Because it was framed.",
    "Why did the cookie cry? Because its mom was a wafer too long.",
    "Why did the skeleton go to the party alone? He had no body to go with.",
    "Why did the lion eat the tightrope walker? He wanted a well-balanced meal.",
    "Why did the mushroom go to the party alone? Because he’s a fungi.",
    "Why don’t some couples go to the gym? Because some relationships don’t work out.",
    "Why did the chicken sit on the cake? Because it wanted to lay a layer.",
    "Why did the man run around his bed? Because he was trying to catch up on his sleep.",
    "Why don’t sharks eat clowns? Because they taste funny.",
    "Why did the bicycle fall over? Because it was two-tired.",
    "Why did the kid bring a ladder to school? Because he wanted to go to high school.",
    "Why did the ghost go into the bar? For the boos.",
    "Why did the scarecrow get a promotion? He was outstanding in his field.",
    "Why don’t seagulls fly over the bay? Because then they’d be bagels.",
    "Why did the chicken cross the road? To get to the other side.",
    "Why did the frog take the bus to work? His car got toad away.",
    "Why did the cat sit on the computer? To keep an eye on the mouse.",
    "Why did the computer go to the doctor? It caught a virus.",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "Why did the cookie go to the hospital? Because he felt crummy.",
    "Why did the math teacher look sad? She had too many problems.",
    "Why did the duck go to rehab? It had a quack addiction.",
    "Why did the baby strawberry cry? Because her parents were in a jam.",
    "Why did the chicken join a band? Because it had the drumsticks.",
    "Why did the man put his money in the blender? He wanted liquid assets.",
    "Why did the mushroom go to the party alone? Because he’s a fungi.",
    "Why did the banana go to the doctor? Because it wasn’t peeling well.",
    "Why did the coffee file a police report? It got mugged.",
    "Why did the golfer bring extra socks? In case he got a hole in one.",
    "Why did the scarecrow get promoted? He was outstanding in his field.",
    "Why did the skeleton go to the party alone? He had no body to go with.",
    "Why did the tomato blush? Because it saw the salad dressing.",
    "Why don’t scientists trust atoms? They make up everything.",
    "Why did the physics teacher break up with the biology teacher? There was no chemistry."
]

# Button to generate a random joke
if st.button("Tell me a joke"):
    joke = random.choice(jokes)
    st.success(joke)
